### ISSUE TITLE
Security PIN protocol

### ISSUE THREAD

**Issue by rockwotj** [bernieplug/plugable-btaps#1]
Hello, I'd love to help knock off one of your TODOs with adding the security PIN features, but need to know the protocol for doing so. Do you have the protocol documented anywhere, or could send me the procedure for the security PIN?

**Comment by craftycorvid** [comment]
Unfortunately there are no protocol docs. The code and docs in this app is the closest thing we have to publicly available docs. 

If you wish to try and implement this missing feature my suggestion is to download the Android app, enable bluetooth logging, and look at the packets being sent to reverse engineer the protocol.

Sorry I can't be of more assistance.
